$script = <<-SHELL
  apt -y update
  apt -y install software-properties-common
  add-apt-repository ppa:deadsnakes/ppa
  apt -y update
  apt -y install python3.8
SHELL

Vagrant.configure("2") do |config|

  config.vm.define("schahid") do |server|
    
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "cloud"

    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider("virtualbox") do |vb|
      
      vb.name = "cloud"
      vb.memory = "2048"
      vb.cpus = 2

    end

    server.vm.provision "shell", inline: $script
  end

end
