---
  - name: Install docker
    hosts: all
    become: true
    user: vagrant

    pre_tasks:
      - name: Update
        apt:
          update_cache: yes
    tasks:
      - name: Install docker dependencies
        apt:
          name: ["ca-certificates", "curl", "gnupg", "python3-pip"]
          state: present 

      - name: Add GPG key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add docker repository to apt
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

      - name: Install Docker Engine, containerd, and Docker Compose
        apt: 
          update_cache: yes
          name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
          state: present

      - name: Install python docker
        pip:
          name: 
            - docker
            - docker-compose
          state: present

  - name: Deploy wordpress with docker-compose
    hosts: all
    become: true
    user: vagrant

    tasks:
      - name: Copy docker resources to the server
        copy:
          src: resources
          dest: /home/{{ ansible_user }}
      
      - name: Create data folder for wordpress
        file:
          path: /home/${USER}/data/wp
          state: directory
          recurse: yes

      - name: Create data folder for database
        file:
          path: /home/${USER}/data/db
          state: directory
          recurse: yes

      - name: Docker compose up
        docker_compose:
          project_src: /home/{{ ansible_user }}/resources
          state: present
          build: yes